#define CARROT_TEXTURE            0
#define EYE_TEXTURE               1
#define ROBOT_FACE_TEXTURE        2
#define GRASS_TEXTURE             3
#define LEAVES_TEXTURE            4
#define NOSE_TEXTURE              5
#define SKY_TEXTURE               6
#define BROWN_TEXTURE             7
#define BROWN_WHITE_BROWN_TEXTURE 8
#define FLESH_TEXTURE             9
#define OCEAN_TEXTURE		 10
#define MOUNTAIN_TEXTURE	 11
#define CLIFF_TEXTURE            12
#define FOREST_TEXTURE           13
#define SAND_TEXTURE             14
#define SHALLOW_TEXTURE          15
#define TUNDRA_TEXTURE           16
